/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo_18_xirpl3_m.huzaer.r.j;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MHRJ
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        txStAwal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tglBerangkat = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txStTjn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jnsKrt = new javax.swing.JComboBox<>();
        tmpDuduk = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        wktBerangkat = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Harga");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Station Awal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 30));

        txStAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txStAwalActionPerformed(evt);
            }
        });
        jPanel1.add(txStAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Station Tujuan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));
        jPanel1.add(tglBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tgl Berangkat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        txStTjn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txStTjnActionPerformed(evt);
            }
        });
        jPanel1.add(txStTjn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kereta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Waktu Berangkat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tempat Duduk");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 30));

        jnsKrt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Ekonomi", "Ekonomi AC", "Bisnis", "Eksekutif" }));
        jPanel1.add(jnsKrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, 30));

        tmpDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        tmpDuduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmpDudukActionPerformed(evt);
            }
        });
        jPanel1.add(tmpDuduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rp.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nama");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 30));

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });
        jPanel1.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 30));

        wktBerangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Pagi", "Siang", "Malam" }));
        jPanel1.add(wktBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 370));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Station Awal", "Station Tujuan", "Tgl Berangkat", "Jenis Kereta", "Waktu Berangkat", "Tempat Duduk", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 760, 490));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, 50));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, 50));

        jButton5.setText("Save");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 40));

        bnEdit.setText("Edit");
        bnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnEditActionPerformed(evt);
            }
        });
        getContentPane().add(bnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 100, 50));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 100, 50));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 100, 50));

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void txStAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txStAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txStAwalActionPerformed

    private void txStTjnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txStTjnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txStTjnActionPerformed

    private void tmpDudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmpDudukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmpDudukActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txID.setText("");
        txNama.setText("");
        txStAwal.setText("");
        txStTjn.setText("");
        txHarga.setText("");
        jnsKrt.setSelectedIndex(0);
        wktBerangkat.setSelectedIndex(0);
        tmpDuduk.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dataFormat = new SimpleDateFormat("yyyy.MM.dd");
        String tanggal = dataFormat.format(tglBerangkat.getDate());
        if("".equals(txID.getText()) || "".equals(txHarga.getText()) || "".equals(txNama.getText()) || "".equals(txStAwal.getText()) || "".equals(txStTjn.getText()) || tglBerangkat.equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
                String jns = "";
                if(jnsKrt.getSelectedItem().equals("Ekonomi")){
                    jns = "Ekonomi";
                }else if(jnsKrt.getSelectedItem().equals("Ekonomi AC")){
                    jns = "Ekonomi AC";
                }else if(jnsKrt.getSelectedItem().equals("Bisnis")){
                    jns = "Bisnis";
                }else if(jnsKrt.getSelectedItem().equals("Eksekutif")){
                    jns = "Eksekutif";
                }
                String wkt = "";
                if(wktBerangkat.getSelectedItem().equals("Pagi")){
                    wkt = "Pagi";
                }else if(wktBerangkat.getSelectedItem().equals("Siang")){
                    wkt = "Siang";
                }else if(wktBerangkat.getSelectedItem().equals("Malam")){
                    wkt = "Malam";
                }
                String ddk = "";
                if(tmpDuduk.getSelectedItem().equals("Gerbong 1")){
                    ddk = "Gerbong 1";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 2")){
                    ddk = "Gerbong 2";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 3")){
                    ddk = "Gerbong 3";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 4")){
                    ddk = "Gerbong 4";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 5")){
                    ddk = "Gerbong 5";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 6")){
                    ddk = "Gerbong 6";
                }
                
                String SQL = "INSERT INTO `tb_pemesanan` (`ID`,`nama`,`stationawal`,`stationtujuan`,`tglberangkat`,`jeniskrt`,`wktberangkat`,`tmpduduk`,`harga`)" + "VALUES('"+txID.getText()+"','"+txNama.getText()+"','"+ txStAwal.getText() +"','"+txStTjn.getText()+"','"+tanggal+"','"+jns+"','"+wkt+"','"+ddk+"','"+txHarga.getText()+"')";
                int status = KoneksiDB.execute(SQL);
                if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else{
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void bnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnEditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dataFormat = new SimpleDateFormat("yyyy.MM.dd");
        String tanggal = dataFormat.format(tglBerangkat.getDate());
        
        if("".equals(txID.getText()) || "".equals(txHarga.getText()) || "".equals(txNama.getText()) || "".equals(txStAwal.getText()) || "".equals(txStTjn.getText()) || tglBerangkat.equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            
            String jns = "";
                if(jnsKrt.getSelectedItem().equals("Ekonomi")){
                    jns = "Ekonomi";
                }else if(jnsKrt.getSelectedItem().equals("Ekonomi AC")){
                    jns = "Ekonomi AC";
                }else if(jnsKrt.getSelectedItem().equals("Bisnis")){
                    jns = "Bisnis";
                }else if(jnsKrt.getSelectedItem().equals("Eksekutif")){
                    jns = "Eksekutif";
                }
                String wkt = "";
                if(wktBerangkat.getSelectedItem().equals("Pagi")){
                    wkt = "Pagi";
                }else if(wktBerangkat.getSelectedItem().equals("Siang")){
                    wkt = "Siang";
                }else if(wktBerangkat.getSelectedItem().equals("Malam")){
                    wkt = "Malam";
                }
                String ddk = "";
                if(tmpDuduk.getSelectedItem().equals("Gerbong 1")){
                    ddk = "Gerbong 1";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 2")){
                    ddk = "Gerbong 2";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 3")){
                    ddk = "Gerbong 3";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 4")){
                    ddk = "Gerbong 4";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 5")){
                    ddk = "Gerbong 5";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 6")){
                    ddk = "Gerbong 6";
                }
                
            String SQL = "UPDATE `tb_pemesanan` SET `nama`='"+txNama.getText()+"',`stationawal`='"+txStAwal.getText()+"',`stationtujuan`='"+txStTjn.getText()+"',`tglberangkat`='"+tanggal+"',`jeniskrt`='"+jns+"',`wktberangkat`='"+wkt+"',`tmpduduk`='"+ddk+"',`harga`='"+txHarga.getText()+"' WHERE `id`='"+txID.getText()+"'";
            int status = KoneksiDB.execute(SQL);
                if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil diedit", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else{
                    JOptionPane.showMessageDialog(this, "Data gagal diedit", "Gagal", JOptionPane.WARNING_MESSAGE);
                }   
        }
    }//GEN-LAST:event_bnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String id = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM `tb_pemesanan` WHERE id = '"+id+"'";
            int status = KoneksiDB.execute(SQL);;
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnEdit;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jnsKrt;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tglBerangkat;
    private javax.swing.JComboBox<String> tmpDuduk;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txStAwal;
    private javax.swing.JTextField txStTjn;
    private javax.swing.JComboBox<String> wktBerangkat;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        //SimpleDateFormat dataFormat = new SimpleDateFormat("yyyy.MM.dd");
        //String tanggal = dataFormat.format(tglBerangkat.getDate());
        String kolom[] = {"id","nama","stationawal","stationtujuan","tglberangkat","jeniskrt","wktberangkat","tmpduduk","harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pemesanan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);;
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String nama = rs.getString(2);
                String stationawal = rs.getString(3);
                String stationtujuan = rs.getString(4);
                String tglberangkat = rs.getString(5);
                String jeniskrt = "";
                if(rs.getString(6).equals("Ekonomi")){
                    jeniskrt = "Ekonomi";
                }else if(rs.getString(6).equals("Ekonomi AC")){
                    jeniskrt = "Ekonomi AC";
                }else if(rs.getString(6).equals("Bisnis")){
                    jeniskrt = "Bisnis";
                }else if(rs.getString(6).equals("Eksekutif")){
                    jeniskrt = "Eksekutif";
                }
                String wktberangkat = "";
                if(rs.getString(7).equals("Pagi")){
                    wktberangkat = "Pagi";
                }else if(rs.getString(7).equals("Siang")){
                    wktberangkat = "Siang";
                }else if(rs.getString(7).equals("Malam")){
                    wktberangkat = "Malam";
                }
                String tmpduduk = "";
                if(rs.getString(8).equals("Gerbong 1")){
                    tmpduduk = "Gerbong 1";
                }else if(rs.getString(8).equals("Gerbong 2")){
                    tmpduduk = "Gerbong 2";
                }else if(rs.getString(8).equals("Gerbong 3")){
                    tmpduduk = "Gerbong 3";
                }else if(rs.getString(8).equals("Gerbong 4")){
                    tmpduduk = "Gerbong 4";
                }else if(rs.getString(8).equals("Gerbong 5")){
                    tmpduduk = "Gerbong 5";
                }else if(rs.getString(8).equals("Gerbong 6")){
                    tmpduduk = "Gerbong 6";
                }
                String harga = rs.getString(9);
                String data[] = {id,nama,stationawal,stationtujuan,tglberangkat,jeniskrt,wktberangkat,tmpduduk,harga};
                dtm.addRow(data);
            }
        }catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
    private void tblDataMouseClicked(java.awt.event.MouseEvent evt){
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            txID.setText(tblData.getValueAt(baris, 0).toString());
            txNama.setText(tblData.getValueAt(baris, 1).toString());
            txStAwal.setText(tblData.getValueAt(baris, 2).toString());
            txStTjn.setText(tblData.getValueAt(baris, 3).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try{
                dateFormat = date.parse(tblData.getValueAt(baris, 4).toString());
            }catch(ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglBerangkat.setDate(dateFormat);
            String jns = tblData.getValueAt(baris, 5).toString();
                if(jns.equals("Ekonomi")){
                    jnsKrt.setSelectedItem("Ekonomi");
                }else if(jns.equals("Ekonomi AC")){
                    jnsKrt.setSelectedItem("Ekonomi AC");
                }else if(jns.equals("Bisnis")){
                    jnsKrt.setSelectedItem("Bisnis");
                }else if(jns.equals("Eksekutif")){
                    jnsKrt.setSelectedItem("Eksekutif");
                }
                String wkt = tblData.getValueAt(baris, 6).toString();;
                if(wkt.equals("Pagi")){
                    wktBerangkat.setSelectedIndex(1);
                }else if(wkt.equals("Siang")){
                    wktBerangkat.setSelectedIndex(2);
                }else if(wkt.equals("Malam")){
                    wktBerangkat.setSelectedIndex(3);
                }
                String ddk = tblData.getValueAt(baris, 7).toString();;
                if(ddk.equals("Gerbong 1")){
                    tmpDuduk.setSelectedIndex(1);
                }else if(ddk.equals("Gerbong 2")){
                    tmpDuduk.setSelectedIndex(2);
                }else if(ddk.equals("Gerbong 3")){
                    tmpDuduk.setSelectedIndex(3);
                }else if(ddk.equals("Gerbong 4")){
                    tmpDuduk.setSelectedIndex(4);
                }else if(ddk.equals("Gerbong 5")){
                    tmpDuduk.setSelectedIndex(5);
                }else if(ddk.equals("Gerbong 6")){
                    tmpDuduk.setSelectedIndex(6);
                }
                txHarga.setText(tblData.getValueAt(baris, 8).toString());
        }
    }
}
