/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo_18_xirpl3_m.huzaer.r.j;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MHRJ
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        txStAwal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tglBerangkat = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txStTjn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jnsKrt = new javax.swing.JComboBox<>();
        tmpDuduk = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        wktBerangkat = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMESANAN TIKET KA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Harga");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });
        jPanel2.add(txHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Station Awal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });
        jPanel2.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, 30));

        txStAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txStAwalActionPerformed(evt);
            }
        });
        jPanel2.add(txStAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Station Tujuan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));
        jPanel2.add(tglBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tgl Berangkat");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        txStTjn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txStTjnActionPerformed(evt);
            }
        });
        jPanel2.add(txStTjn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kereta");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Waktu Berangkat");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tempat Duduk");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 30));

        jnsKrt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Ekonomi", "Ekonomi AC", "Bisnis", "Eksekutif" }));
        jPanel2.add(jnsKrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 30));

        tmpDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        tmpDuduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmpDudukActionPerformed(evt);
            }
        });
        jPanel2.add(tmpDuduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rp.");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nama");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 30));

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });
        jPanel2.add(txID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 190, 30));

        wktBerangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Pagi", "Siang", "Malam" }));
        jPanel2.add(wktBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 340, 370));

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 170, 50));

        btnLogin.setText("LOGIN (ADMIN ONLY)");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 170, 50));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 170, 50));

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 170, 50));

        setSize(new java.awt.Dimension(355, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void txStAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txStAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txStAwalActionPerformed

    private void txStTjnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txStTjnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txStTjnActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void tmpDudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmpDudukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmpDudukActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txID.setText("");
        txNama.setText("");
        txStAwal.setText("");
        txStTjn.setText("");
        txHarga.setText("");
        jnsKrt.setSelectedIndex(0);
        wktBerangkat.setSelectedIndex(0);
        tmpDuduk.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new frmLogin().show();
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dataFormat = new SimpleDateFormat("yyyy.MM.dd");
        String tanggal = dataFormat.format(tglBerangkat.getDate());
        if("".equals(txID.getText()) || "".equals(txHarga.getText()) || "".equals(txNama.getText()) || "".equals(txStAwal.getText()) || "".equals(txStTjn.getText()) || tglBerangkat.equals("")){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
                String jns = "";
                if(jnsKrt.getSelectedItem().equals("Ekonomi")){
                    jns = "Ekonomi";
                }else if(jnsKrt.getSelectedItem().equals("Ekonomi AC")){
                    jns = "Ekonomi AC";
                }else if(jnsKrt.getSelectedItem().equals("Bisnis")){
                    jns = "Bisnis";
                }else if(jnsKrt.getSelectedItem().equals("Eksekutif")){
                    jns = "Eksekutif";
                }
                String wkt = "";
                if(wktBerangkat.getSelectedItem().equals("Pagi")){
                    wkt = "Pagi";
                }else if(wktBerangkat.getSelectedItem().equals("Siang")){
                    wkt = "Siang";
                }else if(wktBerangkat.getSelectedItem().equals("Malam")){
                    wkt = "Malam";
                }
                String ddk = "";
                if(tmpDuduk.getSelectedItem().equals("Gerbong 1")){
                    ddk = "Gerbong 1";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 2")){
                    ddk = "Gerbong 2";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 3")){
                    ddk = "Gerbong 3";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 4")){
                    ddk = "Gerbong 4";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 5")){
                    ddk = "Gerbong 5";
                }else if(tmpDuduk.getSelectedItem().equals("Gerbong 6")){
                    ddk = "Gerbong 6";
                }
                
                String SQL = "INSERT INTO `tb_pemesanan` (`ID`,`nama`,`stationawal`,`stationtujuan`,`tglberangkat`,`jeniskrt`,`wktberangkat`,`tmpduduk`,`harga`)" + "VALUES('"+txID.getText()+"','"+txNama.getText()+"','"+ txStAwal.getText() +"','"+txStTjn.getText()+"','"+tanggal+"','"+jns+"','"+wkt+"','"+ddk+"','"+txHarga.getText()+"')";
                int status = KoneksiDB.execute(SQL);
                if(status == 1){
                    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else{
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jnsKrt;
    private com.toedter.calendar.JDateChooser tglBerangkat;
    private javax.swing.JComboBox<String> tmpDuduk;
    private javax.swing.JTextField txHarga;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txStAwal;
    private javax.swing.JTextField txStTjn;
    private javax.swing.JComboBox<String> wktBerangkat;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
